// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwykwxlyaqvrtxndsjhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3eWt3eGx5YXF2cnR4bmRzamhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjA5NTMsImV4cCI6MjA3MzEzNjk1M30.V5kcR_nDGid99RWYXNx21rim-4oUqK_JnYvMZfcwHvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});